import { writeFile, mkdir, readdir } from "fs/promises";
import { join } from "path";
import { homedir } from "os";
import type { AnalysisResult } from "@sojourn/shared";
import type { BaseSink } from "./base.js";

/**
 * Writes distilled knowledge to Claude Code's memory system.
 * Memory files are stored in ~/.claude/projects/<project>/memory/
 */
export class MemorySink implements BaseSink {
  readonly name = "memory";
  private projectPath: string;

  constructor(projectPath?: string) {
    // Default to current project's memory dir
    this.projectPath =
      projectPath ?? join(homedir(), ".claude", "projects");
  }

  async write(result: AnalysisResult): Promise<void> {
    // Find the project directory based on session IDs
    const memoryDir = await this.findMemoryDir(result.sessionIds[0]);
    await mkdir(memoryDir, { recursive: true });

    const filename = this.generateFilename(result);
    const content = this.formatMemory(result);

    await writeFile(join(memoryDir, filename), content, "utf-8");
  }

  async testConnection(): Promise<boolean> {
    try {
      await readdir(this.projectPath);
      return true;
    } catch {
      return false;
    }
  }

  private async findMemoryDir(sessionId: string): Promise<string> {
    try {
      const projects = await readdir(this.projectPath);
      for (const project of projects) {
        const projectDir = join(this.projectPath, project);
        const files = await readdir(projectDir).catch(() => [] as string[]);
        if (files.some((f) => f.includes(sessionId))) {
          return join(projectDir, "memory");
        }
      }
    } catch {
      // fallback
    }
    // Fallback to a generic memory dir
    return join(this.projectPath, "memory");
  }

  private generateFilename(result: AnalysisResult): string {
    const prefix =
      result.type === "sop"
        ? "sop"
        : result.type === "thought_tree"
          ? "decision"
          : "workflow";
    const slug = this.getSlug(result);
    return `${prefix}_${slug}.md`;
  }

  private getSlug(result: AnalysisResult): string {
    const text =
      result.type === "sop"
        ? ((result as any).title ?? "")
        : result.type === "thought_tree"
          ? ((result as any).rootQuestion ?? "")
          : ((result as any).patternName ?? "");

    return text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40);
  }

  private formatMemory(result: AnalysisResult): string {
    const lines: string[] = [];
    const date = new Date().toISOString().slice(0, 10);

    lines.push("---");
    lines.push(`name: ${this.getTitle(result)}`);
    lines.push(`description: ${this.getDescription(result)}`);
    lines.push(`type: ${result.type === "sop" ? "feedback" : "project"}`);
    lines.push("---\n");

    if (result.type === "sop") {
      const sop = result as any;
      for (let i = 0; i < sop.steps.length; i++) {
        const step = sop.steps[i];
        lines.push(`${i + 1}. ${step.description}`);
        if (step.failureBranch) {
          lines.push(`   - On failure: ${step.failureBranch}`);
        }
      }
    } else if (result.type === "thought_tree") {
      const tree = result as any;
      // Extract key decisions
      const convergences = tree.nodes?.filter(
        (n: any) => n.nodeType === "convergence" && n.reason
      );
      const prunings = tree.nodes?.filter(
        (n: any) => n.nodeType === "pruning" && n.reason
      );

      if (convergences?.length) {
        lines.push("Decisions:");
        for (const n of convergences) {
          lines.push(`- ${n.label}: ${n.reason}`);
        }
      }
      if (prunings?.length) {
        lines.push("\nAvoided approaches:");
        for (const n of prunings) {
          lines.push(`- ${n.label}: ${n.reason}`);
        }
      }
    } else {
      const wf = result as any;
      lines.push(`When: ${wf.trigger}`);
      lines.push(`Do: ${wf.recommendation}`);
    }

    lines.push(`\n_Generated by Sojourn on ${date}_`);
    return lines.join("\n") + "\n";
  }

  private getTitle(result: AnalysisResult): string {
    if (result.type === "sop") return (result as any).title ?? "SOP";
    if (result.type === "thought_tree")
      return (result as any).rootQuestion ?? "Decision";
    return (result as any).patternName ?? "Workflow Pattern";
  }

  private getDescription(result: AnalysisResult): string {
    if (result.type === "sop")
      return (result as any).summary ?? "Extracted SOP from coding conversation";
    if (result.type === "thought_tree")
      return (result as any).summary ?? "Decision tree from coding conversation";
    return `Workflow pattern: ${(result as any).trigger ?? ""}`;
  }
}
